name: Pipeline

on:
  push:
    branches:
      - main
      - 'dto-**'
  pull_request:
    branches: [ main ]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@81cd5ae0920b34eef300e1775313071038a53429
        with:
          php-version: '8.2'
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Run Code style
        run: vendor/bin/phpcs
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse
      - name: Execute Unit tests
        run: vendor/bin/phpunit --testdox
